default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  database: Shipping_project_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: Shipping_project_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: Shipping_project_prod
  pool: 5
  timeout: 5000
